name: phables
channels:
  - conda-forge
  - anaconda
  - bioconda
  - gurobi
dependencies:
  - python>=3.8
  - biopython
  - python-igraph
  - pysam
  - networkx
  - scipy
  - numpy
  - pandas
  - gurobipy
  - more-itertools
  - tqdm
  - click
