name: phables
channels:
  - conda-forge
  - bioconda
  - gurobi
dependencies:
  - python>=3.7
  - biopython
  - python-igraph
  - pysam
  - networkx==2.8.6
  - scipy
  - numpy
  - gurobi
  - tqdm
  - click
