name: phables
channels:
  - conda-forge
  - bioconda
  - ibmdecisionoptimization
dependencies:
  - python >=3.7
  - biopython
  - python-igraph
  - pysam
  - networkx==2.8.6
  - scipy
  - numpy
  - docplex
  - tqdm
  - click
