name: phables
channels:
  - conda-forge
  - anaconda
  - bioconda
  - gurobi
dependencies:
  - python>=3.7
  - biopython
  - python-igraph
  - pysam
  - networkx==2.8.6
  - scipy
  - numpy
  - pandas
  - gurobipy
  - more-itertools
  - tqdm
  - click
  - minimap2
  - samtools
