name: CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
    

jobs:
  tests:
    name: "Python ${{ matrix.python-version }}"
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        python-version: ["3.8", "3.9", "3.10"]

    steps:
      - uses: "actions/checkout@v3"
        with:
          fetch-depth: 0

      # Setup env
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: anaconda-client-env
          environment-file: build/environment.yml
          python-version: ${{ matrix.python-version }}
          auto-activate-base: false

      - name: "Install dependencies on ${{ matrix.os }} for Python ${{ matrix.python-version }}"
        run: |
          python -m pip install --upgrade pip
          pip install .
      
      - name: "Generate coverage report on ${{ matrix.os }} for Python ${{ matrix.python-version }}"
        run: |
          conda install pytest pytest-cov
          pytest --cov=./ --cov-report=xml --cov-append
          
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage.xml
          fail_ci_if_error: true
